CREATE MULTISET TABLE STG_SENSOR_EV ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      PAYLOAD JSON(16776192) INLINE LENGTH 4096 CHARACTER SET LATIN NOT NULL,
      ACQ_DTTM TIMESTAMP(0))
NO PRIMARY INDEX ;